### ISSUE TITLE
java.lang.NoSuchFieldError: impl_peer

### ISSUE THREAD

**Issue by Typhon0** [Thizzer/jtouchbar#27]
Hello, I get this error when I try to show the touch bar with JavaFX. Thanks

```java
Exception in thread "JavaFX Application Thread" java.lang.NoSuchFieldError: impl_peer
	at com.thizzer.jtouchbar.JTouchBarJNI.getJavaFXViewPointer0(Native Method)
	at com.thizzer.jtouchbar.javafx.JavaFXUtils.getViewPointer(JavaFXUtils.java:25)
	at com.thizzer.jtouchbar.JTouchBar$1.run(JTouchBar.java:81)
	at javafx.graphics/com.sun.glass.ui.Application.invokeAndWait(Application.java:466)
	at com.thizzer.jtouchbar.JTouchBar.show(JTouchBar.java:78)
	at JavaFXapp.MainApp.initJtouchBar(MainApp.java:150)
	at JavaFXapp.MainApp.initRootLayout(MainApp.java:91)
	at JavaFXapp.MainApp.initApp(MainApp.java:73)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

My gradle build: 
```gradle
plugins {
    id 'java'
}

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    jcenter()
    maven {
        url  "https://dl.bintray.com/ijabz/maven"
    }
    maven {
        url "http://maven-eclipse.github.io/maven"
    }
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile 'org.kordamp.ikonli:ikonli-core:2.1.1'
    compile 'org.kordamp.ikonli:ikonli-javafx:2.1.1'
    compile 'org.kordamp.ikonli:ikonli-fontawesome5-pack:2.1.1'
    compile 'io.sentry:sentry:1.7.4'
    compile 'org.controlsfx:controlsfx:9.0.0'
    compile 'net.jthink:jaudiotagger:2.2.5'
    compile 'org.xerial:sqlite-jdbc:3.21.0.1'
    compile 'com.thizzer.jtouchbar:jtouchbar:0.1.0'



}

```

**Comment by ttveldhuis** [comment]
What version of Java are you using, Oracle Java or OpenJDK? This error can occur when you are using Java 9 or higher, which are not yet supported at the moment.

Could you post the piece of code where `JTouchBar#show` is called?

**Comment by ttveldhuis** [comment]
This should be fixed with the latest commit. If you could please try using 0.2.0-SNAPSHOT it should be resolved. Otherwise you'll have to wait for the release of 0.2.0.

**Comment by ttveldhuis** [comment]
Fixed for 0.2.0

**Comment by ClementGre** [comment]
Hello, I have the same issue with JavaFX 11 and JavaFX 15 on Open JDK 15.0.1
Every time I try to show the touchbar, I got :
```Java
Exception in thread "JavaFX Application Thread" java.lang.NoSuchFieldError: javafx.stage.Stage.impl_peer Lcom/sun/javafx/tk/TKStage;
	at jtouchbar.javafx@1.0.0/com.thizzer.jtouchbar.javafx.JTouchBarJavaFX.getJavaFXViewPointer0(Native Method)
	at jtouchbar.javafx@1.0.0/com.thizzer.jtouchbar.javafx.JTouchBarJavaFX.getViewPointer(JTouchBarJavaFX.java:52)
	at jtouchbar.javafx@1.0.0/com.thizzer.jtouchbar.javafx.JTouchBarJavaFX.show(JTouchBarJavaFX.java:34)
	at fr.clementgre.pdf4teachers/fr.clementgre.pdf4teachers.interfaces.OSXTouchBarManager.setup(OSXTouchBarManager.java:91)
	at fr.clementgre.pdf4teachers/fr.clementgre.pdf4teachers.interfaces.OSXTouchBarManager.<init>(OSXTouchBarManager.java:29)
	at fr.clementgre.pdf4teachers/fr.clementgre.pdf4teachers.Main.lambda$start$0(Main.java:56)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```


By the way, I had to place manually the `libJTouchBarJavaFX.dylib` file in my Java Libs directory because java didn't found it.
I Build my project with Gradle.

Thank you for your help,
Clement Grennerat

**Comment by ClementGre** [comment]
PS: I checked if it is working with the release 0.2.0 but it is not the case.
