### ISSUE TITLE
JavaFX impl_peer error

### ISSUE THREAD

**Issue by ryandavern** [Thizzer/jtouchbar#40]
Hi! Working with JRE 10 and this error occurs when showing the touch bar. Touch bar works with Swing, but not JavaFX.

Here is the source code of a test application I created https://pastebin.com/WE6cJp1H.

I've definitely made a mistake somewhere so just looking for any help. Thanks :)!

Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:473)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:372)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:941)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:973)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoSuchFieldError: impl_peer
	at com.thizzer.jtouchbar.javafx.JTouchBarJavaFX.getJavaFXViewPointer0(Native Method)
	at com.thizzer.jtouchbar.javafx.JTouchBarJavaFX.getViewPointer(JTouchBarJavaFX.java:52)
	at com.thizzer.jtouchbar.javafx.JTouchBarJavaFX.show(JTouchBarJavaFX.java:34)
	at com.beatplaylist.Main.start(Main.java:51)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:919)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$11(PlatformImpl.java:449)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
Exception running application com.beatplaylist.Main

**Comment by MrDrache333** [comment]
Same here. Same Error but with JavaFX 11

**Comment by schroederonline** [comment]
Hi Thizzer,
the JavaFX implementation does not work with JavaFX 13.0.1
You try to access a field in javafx.stage.Stage.impl_peer which has been renamed to
private TKStage peer;
in class javafx.stage.Window;

Caused by: java.lang.NoSuchFieldError: javafx.stage.Stage.impl_peer Lcom/sun/javafx/tk/TKStage; at com.thizzer.jtouchbar.javafx.JTouchBarJavaFX.getJavaFXViewPointer0(Native Method) at com.thizzer.jtouchbar.javafx.JTouchBarJavaFX.getViewPointer(JTouchBarJavaFX.java:52) at com.thizzer.jtouchbar.javafx.JTouchBarJavaFX.show(JTouchBarJavaFX.java:34)

Regards Marcel
