### ISSUE TITLE
JavaFX 13 support

### ISSUE THREAD

**Issue by schroederonline** [Thizzer/jtouchbar#44]
Hi Thizzer,
the JavaFX implementation does not work with JavaFX 13.0.1
You try to access a field in javafx.stage.Stage.impl_peer which has been renamed to 
private TKStage peer;
in class javafx.stage.Window;

`Caused by: java.lang.NoSuchFieldError: javafx.stage.Stage.impl_peer Lcom/sun/javafx/tk/TKStage;
	at com.thizzer.jtouchbar.javafx.JTouchBarJavaFX.getJavaFXViewPointer0(Native Method)
	at com.thizzer.jtouchbar.javafx.JTouchBarJavaFX.getViewPointer(JTouchBarJavaFX.java:52)
	at com.thizzer.jtouchbar.javafx.JTouchBarJavaFX.show(JTouchBarJavaFX.java:34)`

Regards Marcel

**Comment by schroederonline** [comment]
oh sorry its a duplicate (JavaFX impl_peer error #40)
