### ISSUE TITLE
NullpointerException when running in Java 9

### ISSUE THREAD

**Issue by ttveldhuis** [Thizzer/jtouchbar#7]
Thanks to @AJNeufeld for reporting this (see #6) 

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1328)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1303)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1475)
	at ca.seinesoftware.touchbar.Main.main(Main.java:20)
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: java.awt.Component.getPeer()
 	at com.thizzer.jtouchbar.awt.AWTUtils.getViewPointer(AWTUtils.java:25)
 	at com.thizzer.jtouchbar.JTouchBar.enableForComponent(JTouchBar.java:60)
 	at ca.seinesoftware.touchbar.App.show(Main.java:49)
 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
```

**Comment by ttveldhuis** [comment]
b37ecff is an effort to resolve this by moving the reflection to native code, allowing for more flexibility. Needs to be thoroughly tested.
